// Centralized mock/dummy data for the Autonomous P2P demo.
// All data below is synthetic and used purely for UI demonstration.

export type Priority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type RequisitionStatus =
  | "PENDING"
  | "APPROVED"
  | "AUTO_APPROVED"
  | "REJECTED"
  | "CONVERTED_TO_PO";
export type POStatus = "Draft" | "Sent" | "Acknowledged" | "Partially Received" | "Completed" | "Cancelled";

export interface MatchRow {
  label: string;
  po: string;
  gr: string;
  invoice: string;
  match: boolean;
}

export interface Requisition {
  id: string;
  requester: string;
  sku: string;
  itemName: string;
  quantity: number;
  sourceWarehouse: string;
  destinationDC: string;
  priority: Priority;
  status: RequisitionStatus;
  createdDate: string;
  estimatedCost: number;
}

// `requisitions` used to be a static mock array here. It's now fetched live
// via getRequisitions() in lib/api.ts — see app/requisitions/page.tsx.

export interface Supplier {
  id: string;
  name: string;
  category: string;
  reliabilityScore: number;
  leadTimeDays: number;
  unitCost: number;
  performance: "Preferred" | "Approved" | "Watchlist" | "Under Review";
  onTimeDelivery: number;
  location: string;
  contracts: number;
}

// `suppliers` used to be a static mock array here. It's now fetched live
// via getSuppliers() in lib/api.ts — see app/suppliers/page.tsx.

export interface PurchaseOrder {
  id: string;
  supplier: string;
  requisitionId: string;
  items: string;
  quantity: number;
  amount: number;
  status: POStatus;
  createdDate: string;
  expectedDelivery: string;
  autoGenerated: boolean;
}

// `purchaseOrders` used to be a static mock array here. It's now fetched
// live via getPurchaseOrders() in lib/api.ts — see
// app/purchase-orders/page.tsx.

export interface Shipment {
  id: string;
  poId: string;
  supplier: string;
  warehouse: string;
  orderedQty: number;
  receivedQty: number;
  status: "Awaiting Receipt" | "Partially Received" | "Fully Received" | "Delayed";
  expectedDate: string;
}

export const shipments: Shipment[] = [
  { id: "SHP-4471", poId: "PO-88231", supplier: "MedSource Pharmaceuticals", warehouse: "Delhi Central WH", orderedQty: 1200, receivedQty: 0, status: "Awaiting Receipt", expectedDate: "2026-08-16" },
  { id: "SHP-4470", poId: "PO-88229", supplier: "MedSource Pharmaceuticals", warehouse: "Chennai Cold Chain WH", orderedQty: 600, receivedQty: 420, status: "Partially Received", expectedDate: "2026-08-14" },
  { id: "SHP-4469", poId: "PO-88228", supplier: "Global PackTech Ltd.", warehouse: "Bengaluru Hub", orderedQty: 3000, receivedQty: 3000, status: "Fully Received", expectedDate: "2026-08-13" },
  { id: "SHP-4468", poId: "PO-88227", supplier: "Apex Industrial Supplies", warehouse: "Delhi Central WH", orderedQty: 220, receivedQty: 220, status: "Fully Received", expectedDate: "2026-08-12" },
  { id: "SHP-4467", poId: "PO-88230", supplier: "Sunrise Electronics Co.", warehouse: "Pune Fulfilment Center", orderedQty: 40, receivedQty: 0, status: "Delayed", expectedDate: "2026-08-13" },
];

export interface InvoiceRecord {
  id: string;
  supplier: string;
  poId: string;
  amount: number;
  tax: number;
  quantity: number;
  invoiceDate: string;
  ocrConfidence: number;
  status: "Processed" | "Needs Review" | "Matched" | "Flagged";
}

export const invoices: InvoiceRecord[] = [
  { id: "INV-204", supplier: "MedSource Pharmaceuticals", poId: "PO-88231", amount: 8160, tax: 408, quantity: 1200, invoiceDate: "2026-08-13", ocrConfidence: 98.4, status: "Matched" },
  { id: "INV-198", supplier: "Sunrise Electronics Co.", poId: "PO-88230", amount: 8400, tax: 420, quantity: 40, invoiceDate: "2026-08-12", ocrConfidence: 95.1, status: "Processed" },
  { id: "INV-191", supplier: "Global PackTech Ltd.", poId: "PO-88228", amount: 3810, tax: 190, quantity: 3000, invoiceDate: "2026-08-10", ocrConfidence: 88.7, status: "Flagged" },
  { id: "INV-187", supplier: "Apex Industrial Supplies", poId: "PO-88227", amount: 1870, tax: 93, quantity: 220, invoiceDate: "2026-08-09", ocrConfidence: 99.2, status: "Matched" },
  { id: "INV-180", supplier: "MedSource Pharmaceuticals", poId: "PO-88229", amount: 20880, tax: 1044, quantity: 600, invoiceDate: "2026-08-12", ocrConfidence: 91.5, status: "Needs Review" },
];

export interface Approval {
  id: string;
  invoiceId: string;
  supplier: string;
  amount: number;
  confidence: number;
  reasoning: string;
}

export const approvals: Approval[] = [
  { id: "APR-501", invoiceId: "INV-204", supplier: "MedSource Pharmaceuticals", amount: 8160, confidence: 97, reasoning: "PO quantity, goods receipt and invoice amount align within 0.2% tolerance. Supplier has a 98% on-time and defect-free history over the last 12 months." },
  { id: "APR-502", invoiceId: "INV-180", supplier: "MedSource Pharmaceuticals", amount: 20880, confidence: 74, reasoning: "Invoice amount is 3.1% higher than PO value due to a freight surcharge line not present on the original PO. Recommend manual verification of surcharge terms." },
  { id: "APR-503", invoiceId: "INV-191", supplier: "Global PackTech Ltd.", amount: 3810, confidence: 58, reasoning: "OCR confidence on tax line is below threshold (88.7%) and received quantity has not yet been confirmed in the WMS. Escalation suggested." },
  { id: "APR-504", invoiceId: "INV-198", supplier: "Sunrise Electronics Co.", amount: 8400, confidence: 93, reasoning: "3-way match successful. Minor 1-day delivery variance is within contractual SLA and does not affect payment terms." },
];

export const kpis = {
  pendingRequisitions: 18,
  autoGeneratedPOs: 132,
  ocrSuccessRate: 96.4,
  matchSuccessRate: 91.8,
};

export const procurementTrend = [
  { month: "Feb", requisitions: 210, orders: 178 },
  { month: "Mar", requisitions: 245, orders: 205 },
  { month: "Apr", requisitions: 260, orders: 231 },
  { month: "May", requisitions: 298, orders: 260 },
  { month: "Jun", requisitions: 312, orders: 289 },
  { month: "Jul", requisitions: 356, orders: 320 },
  { month: "Aug", requisitions: 340, orders: 312 },
];

export const poStatusDistribution = [
  { name: "Completed", value: 412, color: "#16a34a" },
  { name: "Sent", value: 96, color: "#2563eb" },
  { name: "Partially Received", value: 58, color: "#d97706" },
  { name: "Draft", value: 24, color: "#94a3b8" },
  { name: "Cancelled", value: 9, color: "#dc2626" },
];

export const spendBySupplier = [
  { supplier: "MedSource", spend: 412000 },
  { supplier: "Sunrise Elec.", spend: 268000 },
  { supplier: "Apex Ind.", spend: 194000 },
  { supplier: "Global PackTech", spend: 152000 },
  { supplier: "NovaMed", spend: 96000 },
  { supplier: "Vertex Chem.", spend: 61000 },
];

export const cycleTimeTrend = [
  { month: "Feb", requisitionToPO: 3.4, invoiceProcessing: 2.1 },
  { month: "Mar", requisitionToPO: 3.1, invoiceProcessing: 2.0 },
  { month: "Apr", requisitionToPO: 2.8, invoiceProcessing: 1.8 },
  { month: "May", requisitionToPO: 2.5, invoiceProcessing: 1.6 },
  { month: "Jun", requisitionToPO: 2.1, invoiceProcessing: 1.3 },
  { month: "Jul", requisitionToPO: 1.8, invoiceProcessing: 1.1 },
  { month: "Aug", requisitionToPO: 1.6, invoiceProcessing: 0.9 },
];

export const touchlessTrend = [
  { month: "Feb", touchless: 48 },
  { month: "Mar", touchless: 54 },
  { month: "Apr", touchless: 58 },
  { month: "May", touchless: 64 },
  { month: "Jun", touchless: 69 },
  { month: "Jul", touchless: 74 },
  { month: "Aug", touchless: 78 },
];

export const monthlyPOVolume = [
  { month: "Feb", volume: 178 },
  { month: "Mar", volume: 205 },
  { month: "Apr", volume: 231 },
  { month: "May", volume: 260 },
  { month: "Jun", volume: 289 },
  { month: "Jul", volume: 320 },
  { month: "Aug", volume: 312 },
];

export const recentActivity = [
  { id: 1, type: "PO Created", detail: "PO-88231 auto-generated for MedSource Pharmaceuticals", time: "8 min ago", status: "success" as const },
  { id: 2, type: "Invoice OCR", detail: "INV-204 extracted with 98.4% confidence", time: "22 min ago", status: "success" as const },
  { id: 3, type: "3-Way Match", detail: "INV-191 flagged — tax line mismatch detected", time: "41 min ago", status: "warning" as const },
  { id: 4, type: "Requisition", detail: "REQ-10232 awaiting manager approval", time: "1 hr ago", status: "neutral" as const },
  { id: 5, type: "Goods Receipt", detail: "SHP-4467 delayed at Pune Fulfilment Center", time: "2 hr ago", status: "danger" as const },
  { id: 6, type: "Approval", detail: "APR-504 auto-approved by AI agent", time: "3 hr ago", status: "success" as const },
];

export const aiRecommendations = [
  {
    id: 1,
    title: "Consolidate Paracetamol orders across 3 warehouses",
    detail: "Delhi, Kolkata and Chennai have overlapping requisitions for MED-2201. Consolidating into a single PO could save an estimated ₹1,03,000 via volume pricing.",
    impact: "High",
  },
  {
    id: 2,
    title: "Switch backup supplier for Industrial Lubricant",
    detail: "Vertex Chemicals & Lubes reliability has dropped to 65%. Apex Industrial Supplies offers a comparable price with 91% on-time delivery.",
    impact: "Medium",
  },
  {
    id: 3,
    title: "Re-negotiate lead time with NovaMed Distribution",
    detail: "Average lead time has grown from 6 to 8 days over the last quarter, risking stockouts for cold-chain SKUs.",
    impact: "Medium",
  },
];
