// Centralized mock/dummy data for the Autonomous P2P demo.
// All data below is synthetic and used purely for UI demonstration.

export type Priority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type RequisitionStatus =
  | "PENDING"
  | "APPROVED"
  | "AUTO_APPROVED"
  | "REJECTED"
  | "CONVERTED_TO_PO";
export type POStatus = "Draft" | "Sent" | "Acknowledged" | "Partially Received" | "Completed" | "Cancelled";

export interface MatchRow {
  label: string;
  po: string;
  gr: string;
  invoice: string;
  match: boolean;
}

export interface Requisition {
  id: string;
  requisitionId: number;
  requester: string;
  sku: string;
  itemName: string;
  quantity: number;
  sourceWarehouse: string;
  destinationDC: string;
  priority: Priority;
  status: RequisitionStatus;
  createdDate: string;
  estimatedCost: number;
  source: "AUTO_P1" | "MANUAL_CHATBOT";
}

// `requisitions` used to be a static mock array here. It's now fetched live
// via getRequisitions() in lib/api.ts — see app/requisitions/page.tsx.

export interface Supplier {
  id: string;
  name: string;
  category: string;
  reliabilityScore: number;
  leadTimeDays: number;
  unitCost: number;
  performance: "Preferred" | "Approved" | "Watchlist" | "Under Review";
  onTimeDelivery: number;
  location: string;
  contracts: number;
  // Raw fields needed to call POST /generate-po for this supplier's one
  // displayed SKU (see app/suppliers/page.tsx) -- not shown in the card UI.
  skuId: string;
  minimumOrderQuantity: number;
  maxCapacityUnitsPerMonth: number;
  currentUtilizationPct: number;
  gmpCertified: boolean;
  defectRatePct: number;
  // Real negotiated net-payment term from data/suppliers.csv (15/30/45/60/90
  // days) -- previously fetched but dropped by transformSupplier(); now used
  // on the printable PO document's Payment Terms row.
  paymentTermsDays: number;
}

// `suppliers` used to be a static mock array here. It's now fetched live
// via getSuppliers() in lib/api.ts — see app/suppliers/page.tsx.

export interface PurchaseOrder {
  id: string;
  supplier: string;
  requisitionId: string;
  items: string;
  quantity: number;
  amount: number;
  status: POStatus;
  createdDate: string;
  expectedDelivery: string;
  autoGenerated: boolean;
  // Already present in po_generation's response (destination_dc) but
  // previously dropped by transformPurchaseOrder() -- exposing it here,
  // not new data.
  destinationDC: string;
}

// `purchaseOrders` used to be a static mock array here. It's now fetched
// live via getPurchaseOrders() in lib/api.ts — see
// app/purchase-orders/page.tsx.

export type DeliveryStatus = "Awaiting Receipt" | "Partially Received" | "Fully Received";

export interface Delivery {
  id: string;
  item: string;
  supplier: string;
  destinationDC: string;
  orderedQty: number;
  receivedQty: number | null;
  status: DeliveryStatus;
  expectedDate: string;
  variancePct: number | null;
  // The linked PO's own status (e.g. "Draft") -- used to only surface POs
  // that have actually been sent to a supplier as awaiting delivery here.
  poStatus: POStatus;
}

// `shipments` used to be a static mock array here (an entity with no real
// counterpart). It's now fetched live via getDeliveries() in lib/api.ts,
// built directly from real purchase_orders + goods_receipts — see
// app/goods-receipt/page.tsx.

export type InvoiceStatus =
  | "Awaiting Delivery"
  | "Needs Review"
  | "Matched"
  | "Flagged"
  | "Manually Approved"
  | "Rejected"
  | "Escalated";

export interface InvoiceRecord {
  id: string;
  supplier: string;
  poId: string;
  quantity: number | null;
  amount: number | null;
  status: InvoiceStatus;
  printablePath: string | null;
  // Predictive Anomaly Detection -- distinct from `status` above (which is
  // derived from the reactive 3-way-match tolerance check). This flags
  // deviation from THIS supplier's own historical invoice pattern instead.
  isPredictiveAnomaly?: boolean;
  predictiveAnomalyReason?: string | null;
}

// `invoices` used to be a static mock array here (with tax/invoiceDate/
// ocrConfidence fields that don't exist in real data). It's now fetched
// live via getInvoices() in lib/api.ts — see app/invoices/page.tsx.

export interface Approval {
  id: string;
  invoiceId: string;
  supplier: string;
  amount: number;
  confidence: number;
  reasoning: string;
}

// `approvals` used to be a static mock array here. It's now fetched live
// via getApprovals() in lib/api.ts — see app/approvals/page.tsx.

// pendingRequisitions, autoGeneratedPOs and matchSuccessRate used to live
// here too -- Dashboard now computes those live from getRequisitions()/
// getPurchaseOrders()/getInvoiceMatches() (lib/api.ts). ocrSuccessRate
// stays mock: not in scope (no real OCR-confidence signal to wire it to).
export const kpis = {
  ocrSuccessRate: 96.4,
};

export const procurementTrend = [
  { month: "Feb", requisitions: 210, orders: 178 },
  { month: "Mar", requisitions: 245, orders: 205 },
  { month: "Apr", requisitions: 260, orders: 231 },
  { month: "May", requisitions: 298, orders: 260 },
  { month: "Jun", requisitions: 312, orders: 289 },
  { month: "Jul", requisitions: 356, orders: 320 },
  { month: "Aug", requisitions: 340, orders: 312 },
];

export const poStatusDistribution = [
  { name: "Completed", value: 412, color: "#16a34a" },
  { name: "Sent", value: 96, color: "#2563eb" },
  { name: "Partially Received", value: 58, color: "#d97706" },
  { name: "Draft", value: 24, color: "#94a3b8" },
  { name: "Cancelled", value: 9, color: "#dc2626" },
];

export const spendBySupplier = [
  { supplier: "MedSource", spend: 412000 },
  { supplier: "Sunrise Elec.", spend: 268000 },
  { supplier: "Apex Ind.", spend: 194000 },
  { supplier: "Global PackTech", spend: 152000 },
  { supplier: "NovaMed", spend: 96000 },
  { supplier: "Vertex Chem.", spend: 61000 },
];

export const cycleTimeTrend = [
  { month: "Feb", requisitionToPO: 3.4, invoiceProcessing: 2.1 },
  { month: "Mar", requisitionToPO: 3.1, invoiceProcessing: 2.0 },
  { month: "Apr", requisitionToPO: 2.8, invoiceProcessing: 1.8 },
  { month: "May", requisitionToPO: 2.5, invoiceProcessing: 1.6 },
  { month: "Jun", requisitionToPO: 2.1, invoiceProcessing: 1.3 },
  { month: "Jul", requisitionToPO: 1.8, invoiceProcessing: 1.1 },
  { month: "Aug", requisitionToPO: 1.6, invoiceProcessing: 0.9 },
];

export const touchlessTrend = [
  { month: "Feb", touchless: 48 },
  { month: "Mar", touchless: 54 },
  { month: "Apr", touchless: 58 },
  { month: "May", touchless: 64 },
  { month: "Jun", touchless: 69 },
  { month: "Jul", touchless: 74 },
  { month: "Aug", touchless: 78 },
];

export const monthlyPOVolume = [
  { month: "Feb", volume: 178 },
  { month: "Mar", volume: 205 },
  { month: "Apr", volume: 231 },
  { month: "May", volume: 260 },
  { month: "Jun", volume: 289 },
  { month: "Jul", volume: 320 },
  { month: "Aug", volume: 312 },
];

export const recentActivity = [
  { id: 1, type: "PO Created", detail: "PO-88231 auto-generated for MedSource Pharmaceuticals", time: "8 min ago", status: "success" as const },
  { id: 2, type: "Invoice OCR", detail: "INV-204 extracted with 98.4% confidence", time: "22 min ago", status: "success" as const },
  { id: 3, type: "3-Way Match", detail: "INV-191 flagged — tax line mismatch detected", time: "41 min ago", status: "warning" as const },
  { id: 4, type: "Requisition", detail: "REQ-10232 awaiting manager approval", time: "1 hr ago", status: "neutral" as const },
  { id: 5, type: "Goods Receipt", detail: "SHP-4467 delayed at Pune Fulfilment Center", time: "2 hr ago", status: "danger" as const },
  { id: 6, type: "Approval", detail: "APR-504 auto-approved by AI agent", time: "3 hr ago", status: "success" as const },
];

export const aiRecommendations = [
  {
    id: 1,
    title: "Consolidate Paracetamol orders across 3 warehouses",
    detail: "Delhi, Kolkata and Chennai have overlapping requisitions for MED-2201. Consolidating into a single PO could save an estimated ₹1,03,000 via volume pricing.",
    impact: "High",
  },
  {
    id: 2,
    title: "Switch backup supplier for Industrial Lubricant",
    detail: "Vertex Chemicals & Lubes reliability has dropped to 65%. Apex Industrial Supplies offers a comparable price with 91% on-time delivery.",
    impact: "Medium",
  },
  {
    id: 3,
    title: "Re-negotiate lead time with NovaMed Distribution",
    detail: "Average lead time has grown from 6 to 8 days over the last quarter, risking stockouts for cold-chain SKUs.",
    impact: "Medium",
  },
];
