"use client";
import * as React from "react";
import { Download, Send, FileText, Bot } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { purchaseOrders, type PurchaseOrder } from "@/lib/data";
import { formatCurrency } from "@/lib/utils";

export default function PurchaseOrdersPage() {
  const [selected, setSelected] = React.useState<PurchaseOrder>(purchaseOrders[0]);

  return (
    <div className="animate-fade-in">
      <PageHeader
        title="Purchase Orders"
        description={`${purchaseOrders.length} purchase orders • ${purchaseOrders.filter((p) => p.autoGenerated).length} auto-generated by AI`}
      />

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-5">
        <Card className="xl:col-span-3">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>PO ID</TableHead>
                <TableHead>Supplier</TableHead>
                <TableHead>Items</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Amount</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {purchaseOrders.map((po) => (
                <TableRow
                  key={po.id}
                  onClick={() => setSelected(po)}
                  className={
                    "cursor-pointer " + (selected.id === po.id ? "bg-primary-50 dark:bg-primary-500/10" : "")
                  }
                >
                  <TableCell className="font-medium text-primary-700 dark:text-primary-400">
                    <div className="flex items-center gap-1.5">
                      {po.id}
                      {po.autoGenerated && (
                        <span title="Auto-generated by AI">
                          <Bot size={12} className="text-primary-500" />
                        </span>
                      )}
                    </div>
                  </TableCell>
                  <TableCell>{po.supplier}</TableCell>
                  <TableCell className="text-muted-foreground">{po.items}</TableCell>
                  <TableCell>
                    <StatusBadge status={po.status} />
                  </TableCell>
                  <TableCell className="text-right font-medium">{formatCurrency(po.amount)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>

        <Card className="xl:col-span-2">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>PO Preview</CardTitle>
                <CardDescription>{selected.id}</CardDescription>
              </div>
              <StatusBadge status={selected.status} />
            </div>
          </CardHeader>
          <CardContent>
            <div className="rounded-lg border border-dashed border-border bg-secondary/40 p-5">
              <div className="flex items-center gap-2 border-b border-border pb-3">
                <FileText className="text-primary-600" size={20} />
                <div>
                  <p className="text-sm font-bold text-foreground">Purchase Order — {selected.id}</p>
                  <p className="text-xs text-muted-foreground">Generated {selected.createdDate}</p>
                </div>
              </div>

              <dl className="mt-3 space-y-2 text-xs">
                <div className="flex justify-between">
                  <dt className="text-muted-foreground">Supplier</dt>
                  <dd className="font-medium text-foreground">{selected.supplier}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-muted-foreground">Linked requisition</dt>
                  <dd className="font-medium text-foreground">{selected.requisitionId}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-muted-foreground">Line item</dt>
                  <dd className="font-medium text-foreground">{selected.items}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-muted-foreground">Quantity</dt>
                  <dd className="font-medium text-foreground">{selected.quantity.toLocaleString()}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-muted-foreground">Expected delivery</dt>
                  <dd className="font-medium text-foreground">{selected.expectedDelivery}</dd>
                </div>
                <div className="flex justify-between border-t border-border pt-2 text-sm">
                  <dt className="font-semibold text-foreground">Total amount</dt>
                  <dd className="font-bold text-primary-700 dark:text-primary-400">{formatCurrency(selected.amount)}</dd>
                </div>
              </dl>

              {selected.autoGenerated && (
                <Badge variant="info" className="mt-3">
                  <Bot size={12} /> Auto-generated by AI Agent
                </Badge>
              )}
            </div>

            <div className="mt-4 flex gap-2">
              <Button className="flex-1" variant="outline">
                <Download size={15} /> Download PO
              </Button>
              <Button className="flex-1">
                <Send size={15} /> Send to Supplier
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
